export const CREATE_STATION_START ='CREATE_STATION_START';
export const CREATE_STATION_SUCCESS ='CREATE_STATION_SUCCESS';
export const CREATE_STATION_ERROR ='CREATE_STATION_ERROR';

export const UPDATE_STATION_START ='UPDATE_STATION_START';
export const UPDATE_STATION_SUCCESS ='UPDATE_STATION_SUCCESS';
export const UPDATE_STATION_ERROR ='UPDATE_STATION_ERROR';

export const GET_CUR_STATION_START = 'GET_CUR_STATION_START';
export const GET_CUR_STATION_SUCCESS = 'GET_CUR_STATION_SUCCESS';
export const GET_CUR_STATION_ERROR = 'GET_CUR_STATION_ERROR';