export const CREATE_STOCK_START = 'CREATE_STOCK_START';
export const CREATE_STOCK_SUCCESS = 'CREATE_STOCK_SUCCESS';
export const CREATE_STOCK_ERROR = 'CREATE_STOCK_ERROR';

export const GET_STOCKS_START = 'GET_STOCKS_START';
export const GET_STOCKS_SUCCESS = 'GET_STOCKS_SUCCESS';
export const GET_STOCKS_ERROR = 'GET_STOCKS_ERROR';

export const EDIT_STOCK_START = 'EDIT_STOCK_START';
export const EDIT_STOCK_SUCCESS = 'EDIT_STOCK_SUCCESS';
export const EDIT_STOCK_ERROR = 'EDIT_STOCK_ERROR';

export const GET_SELLED_STOCK_START ='GET_SELLED_STOCK_START';
export const GET_SELLED_STOCK_SUCCESS ='GET_SELLED_STOCK_SUCCESS';
export const GET_SELLED_STOCK_ERROR ='GET_SELLED_STOCK_ERROR';