export const GET_TRANSACTIONS_START ='GET_TRANSACTIONS_START';
export const GET_TRANSACTIONS_SUCCESS ='GET_TRANSACTIONS_SUCCESS';
export const GET_TRANSACTIONS_ERROR ='GET_TRANSACTIONS_ERROR';

export const SELL_START = 'SELL_START';
export const SELL_SUCCESS = 'SELL_SUCCESS';
export const SELL_ERROR = 'SELL_ERROR';

export const RECHARGE_START = 'RECHARGE_START';
export const RECHARGE_SUCCESS = 'RECHARGE_SUCCESS';
export const RECHARGE_ERROR = 'RECHARGE_ERROR';