export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const GET_CURR_USER_START = 'GET_CURR_USER_START';
export const GET_CURR_USER_SUCCESS = 'GET_CURR_USER_SUCCESS';
export const GET_CURR_USER_ERROR = 'GET_CURR_USER_ERROR';